ExperimentBasePath: "/orfeo/cephfs/scratch/area/ntosato/pippo/ForwardForward-machiavelli/submission-frozen/"

Experiments:
  - experiment:
      model: ff
      learningRate:
        - 0.01
      epochs:
        - 1200
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: mnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: ff
      learningRate:
        - 0.01
      epochs:
        - 100
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: fashionmnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024


  - experiment:
      model: bp_ff
      learningRate:
        - 0.0001
      epochs:
        - 300
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: fashionmnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp_ff
      learningRate:
        - 0.0001
      epochs:
        - 300
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: mnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp
      learningRate:
        - 0.0001
      epochs:
        - 80
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: fashionmnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024
  - experiment:
      model: bp
      learningRate:
        - 0.0001
      epochs:
        - 80
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: mnist
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: ff
      learningRate:
        - 0.0001
      epochs:
        - 1000
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: svhn
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: ff
      learningRate:
        - 0.0001
      epochs:
        - 1000
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: cifar
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp_ff
      learningRate:
        - 0.0001
      epochs:
        - 200
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: svhn
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp_ff
      learningRate:
        - 0.0001
      epochs:
        - 200
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: cifar
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024


  - experiment:
      model: bp
      learningRate:
        - 0.0001
      epochs:
        - 80
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: svhn
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp
      learningRate:
        - 0.0001
      epochs:
        - 80
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: cifar
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024

  - experiment:
      model: bp
      learningRate:
        - 0.0001
      epochs:
        - 80
      threshold:
        - 3
      nonLinearity: relu
      repetitionCount: 10
      enable: true
      customPath: none
      dataSet: svhn
      norm: 2
      nLayers: 3
      dropout: 0.0
      batch_size: 1024
